### ISSUE TITLE
Have alias names ending in `num`, `int`, `obj` etc. trigger autocompletion for their respective categories

### ISSUE THREAD

**Issue by Unfunkable** [Unfunkable/VSCode-ReachVariantTool#23]
Including ones with numbers at the end. Typically `temp_int01` or some similar variation is seen. Should make it much easier to use if aliases don't need to end with the full word (number, object, etc.)

**Comment by faris0064** [comment]
it just occurred to me that there's nothing to autocomplete for numbers so idk why i brought them up
